### PR TITLE
Fix .equalTo, .endAt, and .startAt filters when used without key.

### PR DESCRIPTION
**Pull request by janvogt**
- When used without key they contained a spurious comma, since
['equalTo', ['a', undefined]].join(':') is 'equalTo:a,' (with comma at the end) and not  'equalTo:a' which would be the result of ['equalTo', ['a']].join(':').

### CODE REVIEW

**Comment by janvogt** [comment]
BTW: Possibility to do so is in the official documentation e.g.: https://firebase.google.com/docs/reference/js/firebase.database.Reference#equalTo

**Comment by Salakar** [comment]
I think this may have been fixed in the v3 branch, could you have a look? If not could you do a PR to my fork and I'll merge it into v3

**Comment by janvogt** [comment]
I can't test it right now, but looking at the code it does seem to be fixed there. When will you release v3 to the NPM repo?

**Comment by Salakar** [comment]
Hopefully have an alpha version out soon

**Comment by Salakar** [comment]
RC1 out on npm, can confirm this is working. Closing

**Pull request closed without merging**
