### PR TITLE
[Anonymous signin]

### PR DESCRIPTION
**Pull request by julien-innovantic**
Adding anonymously signin on android and IOS firebase native modules.

### CODE REVIEW

**Comment by auser** [comment]
Looks great! I'll test it out tonight.

**Comment by auser** [comment]
@julien-innovantic I don't see any way to access the anonymous login through the JS api. Am I missing it?

**Comment by julien-innovantic** [comment]
@auser : in my commit, i don't call directly the js, i do it in my firebase service.
 But if you want test it, it's like in your example:

const firestack = new Firestack(configurationOptions);
firestack.signInAnonymously();

Or if you want get the associated user:

firestack.signInAnonymously().then( user => {
      console.log(user.uid)
});

**Comment by julien-innovantic** [comment]
@auser : Ok i understand :p 
Sorry, i don't see this missing file.  So now, it should works.

**Comment by prescottprue** [comment]
@auser [Here are the docs for that js method](https://firebase.google.com/docs/auth/web/anonymous-auth)

**Comment by auser** [comment]
Added and merged in.

**Pull request closed without merging**
