### PR TITLE
Add firebase cloud messaging

### PR DESCRIPTION
**Pull request by slycoder**
* Update the Pods to include FirebaseMessaging
* Add a ‘configured’ option so that we can get a Firestack object while
skipping configuration (in case you know that it’s been configured in
AppDelegate)

### CODE REVIEW

**Comment by auser** [comment]
Hey thanks for the pull! 

I can't merge this yet as I can't get it to compile for me without throwing an error (I believe, this is initial investigation due to the GIPReachability library checking for a listener). How do you think we can/should provide a listener for the user who is _not_ using the `AppDelegate` to set up a listener? 

I think imagine setting up a listener automatically that emits a JS event by default and allowing the user to set up a JS listener manually. Perhaps you have a better idea?

**Comment by slycoder** [comment]
Lemme try to fiddle with it (xcode is a bear sometimes) and see if it compiles for me; do you have a test harness handy that you're using to build?

**Comment by auser** [comment]
@slycoder cool... yeah, Xcode can be a pain. I just have a sample app... I haven't found a convenient testing method _yet_ beyond use... embarrassing, I know.

**Comment by slycoder** [comment]
Hm, I was able to get it to build out-of-the-box.  Just did the following:

  react-native init firestack_example

Then installed firebase and this branch of firestack.  Here's my package.json:

```
{
  "name": "firestack_example",
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "start": "node node_modules/react-native/local-cli/cli.js start"
  },
  "dependencies": {
    "firebase": "^3.3.0",
    "react": "15.2.1",
    "react-native": "0.31.0",
    "react-native-firestack": "git+https://github.com/slycoder/react-native-firestack#1ca2a72b37a019ecabd1f6ccae850af17d019b30"
  }
}
```

Do you know where your build is failing?

**Comment by auser** [comment]
I apologize. It's not for building where the error is, it's running. I believe GCM requires a callback to be registered on launch. What does your AppDelegate look like?

**Comment by auser** [comment]
Yep. This works locally for me. I'll merge it in! Thanks for the contribution!

Do you have an idea on what the JS API should look like?

**Comment by slycoder** [comment]
I think react-native-fcm actually has as good bead on this, hopefully we can figure out a way to integrate some of those ideas here and have a one-stop shop for this stuff.

**Pull request merged**
