### PR TITLE
Fix Storage on android

### PR DESCRIPTION
**Pull request by BlooJeans**

### CODE REVIEW

**Comment by Salakar** [comment]
Implemented on my branch. (Just making a note)

**Comment by szujak** [comment]
Omg, thanks for that pr. I was wondering why I get `{ message: 'User does not have permission to access this object.', code: 1 }` all the time :( and this fix problem for me! 👍

**Comment by Salakar** [comment]
@szujak this is implemented on the v3 branch if you want to try it out

**Comment by szujak** [comment]
@Salakar I got one problem with branch `v3`.

how to register something like this:
`firestack.database().ref(`user-data/${uid}/settings`).on('value', this.onSettingsChange);`
now it throws an error :(

`FirestackDatabase.on got 4 arguments, expected 5`
`FirestackDatabase.on got 3 arguments, expected 4`

**Comment by kyle-ssg** [comment]
Hey @Salakar , thanks for creating such an awesome project - everything so far is working fantastic except android storage. I gave this a go on the v3 branch - database worked without any changes however storage seems to throw an exception:

```
11-20 14:26:01.013  4089  5584 I FirestackStorage: From file: /storage/emulated/0/DCIM/Camera/IMG_20161120_131408.jpg to gs://project-4251246165915577329.appspot.com with name img

11-20 14:26:01.014  4089  5584 I System.out: Transferred 0.0/5175.0(0.0% complete)

11-20 14:26:01.014  4089  5584 I System.out: Transferred 0.0/5175.0(0.0% complete)

11-20 14:26:01.014  4089  5894 W GooglePlayServicesUtil: Google Play Store is missing.

11-20 14:26:01.014  4089  5894 W DynamiteModule: Local module descriptor class for com.google.android.gms.firebasestorage not found.

11-20 14:26:01.014  4089  5894 I DynamiteModule: Considering local module com.google.android.gms.firebasestorage:0 and remote module com.google.android.gms.firebasestorage:0

11-20 14:26:01.014  4089  5894 E NetworkRqFactoryProxy: NetworkRequestFactoryProxy failed with a RemoteException:

11-20 14:26:01.014  4089  5894 E NetworkRqFactoryProxy: com.google.android.gms.internal.zztl$zza: No acceptable module found. Local version is 0 and remote version is 0.

11-20 14:26:01.014  4089  5894 E NetworkRqFactoryProxy: 	at com.google.android.gms.internal.zztl.zza(Unknown Source)

11-20 14:26:01.014  4089  5894 E NetworkRqFactoryProxy: 	at com.google.android.gms.internal.zztl.zza(Unknown Source)

11-20 14:26:01.014  4089  5894 E NetworkRqFactoryProxy: 	at com.google.android.gms.internal.zzaol.<init>(Unknown Source)

11-20 14:26:01.014  4089  5894 E NetworkRqFactoryProxy: 	at com.google.android.gms.internal.zzaol.zzj(Unknown Source)

11-20 14:26:01.014  4089  5894 E NetworkRqFactoryProxy: 	at com.google.firebase.storage.StorageReference.an(Unknown Source)

11-20 14:26:01.014  4089  5894 E NetworkRqFactoryProxy: 	at com.google.firebase.storage.UploadTask.aA(Unknown Source)

11-20 14:26:01.014  4089  5894 E NetworkRqFactoryProxy: 	at com.google.firebase.storage.UploadTask.run(Unknown Source)

11-20 14:26:01.014  4089  5894 E NetworkRqFactoryProxy: 	at com.google.firebase.storage.StorageTask$8.run(Unknown Source)

11-20 14:26:01.014  4089  5894 E NetworkRqFactoryProxy: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)

11-20 14:26:01.014  4089  5894 E NetworkRqFactoryProxy: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)

11-20 14:26:01.014  4089  5894 E NetworkRqFactoryProxy: 	at java.lang.Thread.run(Thread.java:818)

11-20 14:26:01.014  4089  5894 E UploadTask: Unable to create a network request from metadata
```

Code to attempt upload was as follows

```
		var storage = firebase.storage();
		storage.setStorageUrl(Project.firebase.storageBucket)
		storage.uploadFile("img", file.uri, {
			contentType: 'image/jpeg',
			contentEncoding: 'base64',
		})
			.then((res) => alert('The file has been uploaded'))
			.catch(err => console.error('There was an error uploading the file', err))
```

Is there something I'm doing wrong, or perhaps that this won't work without google play services under simulator? Thanks.

**Comment by BlooJeans** [comment]
@szujak The database error was solved in https://github.com/fullstackreact/react-native-firestack/pull/154 , which is now merged into the v3 branch.  If you can't / don't want to use v3 yet, then you can cherry pick the database fix from d50e976 (just remove react-native-firestack/lib/modules/database.js )

**Pull request merged**
