### PR TITLE
[v3] [ios] transaction

### PR DESCRIPTION
**Pull request by FrankSalad**
@auser I hope this is similar to what you might've done for #78. It's a little bit brittle - it can leak if the `beginTransaction` call isn't followed up with a `tryCommitTransaction`. If you had a different implementation strategy in mind I'd like to know :man_cartwheeling:

### CODE REVIEW

**Comment by Ehesp** [comment]
cc @Salakar @chrisbianca

**Comment by FrankSalad** [comment]
Looking at the concurrency again, I don't understand why the 'dispatch_barrier_async' within the 'dispatch_async' call doesn't deadlock every time. Does GCD run the barrier block when it notices the outer block running 'dispatch_semaphore_wait'?

All the docs say barrier blocks do not execute while other blocks on the same queue are executing. Does waiting on a semaphore not count as executing on the queue?

I'm still kind of green when it comes to native code. @auser I'll add info in the docs asap. Thanks.

**Comment by auser** [comment]
@FrankSalad lmk when you add to the docs. As far as the dispatch async, it does 'queue' it AFAIK, so I think that should work just fine

**Comment by FrankSalad** [comment]
@auser I was trying to follow https://mikeash.com/pyblog/friday-qa-2011-10-14-whats-new-in-gcd.html

**Comment by Salakar** [comment]
@FrankSalad nice work, can we get this in on android also if anyone has time to do it?

cc @Ehesp @chrisbianca

**Pull request merged**
