### PR TITLE
update readme to show no longer maintain

### PR DESCRIPTION
**Pull request by beskytter**
Hi, I found many issue when I tried using this today for my app but I see reading from comment in issues that this no longer maintain? I think to avoid the time wasting for other people the readme should say that it no longer maintain and seek other libraries. 

I not sure which other libraries to suggest so I add link to npm search for `react native firebase` - there some other library there, maybe someone suggest?

Thanks you

### CODE REVIEW

**Comment by Salakar** [comment]
Thanks for the PR @beskytter - whilst I agree with this and can merge this myself, I think it'd only be fair if @auser responded / took action on this - as ultimately it's his repo, I will DM him and see if I can get a response.

**Comment by beskytter** [comment]
@Salakar oh ok . thanks anyway

**Comment by Salakar** [comment]
I tweeted ari and he responded saying he'd reply when he got to his keyboard, this was 3 days ago. I'll just merge, most of us are tired of waiting around.

https://twitter.com/mikediarmid/status/869963067291037696

**Comment by muescha** [comment]
@salakar i think it would be ok if you also Point to your fork of this repo in the readme (additional to the np search)

**Pull request merged**
